In [346]:
from openpyxl import load_workbook
import numpy as np
import pandas as pd
import requests

In [347]:
with open(f"retail-sales_total.xlsx", "wb") as f:
    x = (f'https://www.ons.gov.uk/file?'
         f'uri=%2fbusinessindustryandtrade'
         f'%2fretailindustry%2fdatasets'
         f'%2fpoundsdatatotalretailsales'
         f'%2fcurrent/poundsdata1.xlsx')
    f.write(requests.get(x).content)

with open(f"retail-sales_internet.xlsx", "wb") as f:
    x = (f'https://www.ons.gov.uk/file?'
         f'uri=%2fbusinessindustryandtrade'
         f'%2fretailindustry%2fdatasets'
         f'%2fretailsalesindexinternetsales'
         f'%2fcurrent/internetsalesreferencetables.xlsx')
    f.write(requests.get(x).content)

In [ ]:
# SCRATCHPAD

# for i, row in df.iterrows():
# 	print(f"Index: {i}")
# 	print(f"{row}\n")
 
# for row in df.itertuples(index=False):
#     print(row)
    
# flat_list = [item for sublist in x for item in sublist]
# df.where(df.notnull(), None)

In [356]:
wb = load_workbook('retail-sales_internet.xlsx')
x = []

for row in wb.worksheets[2].iter_rows(min_row=7, max_col=None, max_row=None, values_only=True):
    x.append(row)

df = pd.DataFrame(x[7:],columns=x[0]).fillna(value=np.nan)
df = df.rename(columns={df.columns[0]: "date"})
df.iloc[:,0] = df.iloc[:,0].ffill()
x = list(df.columns)
x[0] = 'year'
df.columns = x
df['year'] = df['year'].astype(str).replace('\.0', '', regex=True)
df['Date'] = df[['year','date']].agg(' '.join, axis=1)
df = df.set_index('Date').drop(['year', 'date'], axis=1)
df = df * (52/12)
df.index = pd.to_datetime(df.index)
df

,All retailing excluding automotive fuel,Predominantly food stores,Total,Non-specialised stores,"Textile, clothing and footwear stores",Household goods stores,Other stores,Non-store retailing
Date,,,,,,,,
2008-01-01,966.333333,170.300000,396.933333,71.066667,102.700000,94.466667,128.266667,399.533333
2008-02-01,1022.666667,169.866667,426.833333,77.133333,113.533333,101.400000,134.766667,425.966667
2008-03-01,1046.500000,170.733333,432.466667,78.000000,114.833333,104.866667,134.766667,443.300000
2008-04-01,1098.933333,178.100000,453.266667,80.600000,118.300000,110.933333,143.433333,467.566667
2008-05-01,1113.233333,182.000000,458.033333,83.633333,120.900000,112.233333,141.266667,473.200000
...,...,...,...,...,...,...,...,...
2021-06-01,10074.133333,1566.066667,3802.933333,759.633333,1122.766667,870.133333,1050.400000,4705.133333
2021-07-01,9736.133333,1596.833333,3666.000000,757.033333,1113.666667,791.266667,1004.033333,4472.866667
2021-08-01,9860.933333,1560.866667,3720.166667,750.100000,1135.766667,781.300000,1053.000000,4579.900000
2021-09-01,9889.966667,1563.466667,3678.133333,782.600000,1095.900000,749.666667,1049.533333,4648.366667
2021-10-01,9827.566667,1535.300000,3681.166667,774.800000,1109.333333,730.600000,1066.000000,4611.100000

In [355]:
wb = load_workbook('retail-sales_total.xlsx')
x = []

for row in wb.worksheets[9].iter_rows(min_row=7, max_col=None, max_row=None, values_only=True):
    x.append(row)

df = pd.DataFrame(x[4:],columns=x[0]).rename({None: 'Date'}, axis=1).set_index('Date').fillna(value=np.nan)
df = df.dropna(axis=0, how='all').drop(df.columns[12:], axis=1)
df = df.drop(df.columns[1::-1], axis=1)
df.drop('Automotive fuel', axis=1)
df.index = pd.to_datetime(df.index)
df

,All Retailing excluding automotive fuel,Predominantly food stores,Total,Non-specialised stores,"Textile, clothing and footwear stores",Household goods stores,Other stores,Non-store retailing,Automotive fuel
Date,,,,,,,,,
1994-01-01,13098758.0,5262001.0,6909100.0,1202474.0,1764226.0,1745610.0,2196790.0,927657.0,NaN
1994-02-01,12850749.0,5217322.0,6691698.0,1142494.0,1706435.0,1678974.0,2163795.0,941729.0,NaN
1994-03-01,16303609.0,6548609.0,8591931.0,1483473.0,2209544.0,2116585.0,2782329.0,1163069.0,NaN
1994-04-01,12972631.0,5250410.0,6776972.0,1164800.0,1753226.0,1700027.0,2158919.0,945249.0,NaN
1994-05-01,13114290.0,5266231.0,6888685.0,1170297.0,1760307.0,1708970.0,2249111.0,959374.0,NaN
...,...,...,...,...,...,...,...,...,...
2021-06-01,42087937.0,17453171.0,18029832.0,3271002.0,4497018.0,3990541.0,6271271.0,6604934.0,4175804.0
2021-07-01,32664159.0,13661875.0,13853795.0,2587848.0,3529697.0,3036424.0,4699826.0,5148489.0,3486583.0
2021-08-01,32559797.0,13543643.0,13914456.0,2529567.0,3611098.0,3012687.0,4761104.0,5101698.0,3527534.0
2021-09-01,40637557.0,17056577.0,17287676.0,3273458.0,4562657.0,3524069.0,5927492.0,6293304.0,4550437.0
2021-10-01,33184516.0,13663876.0,14497290.0,2649117.0,3875633.0,2874825.0,5097715.0,5023350.0,3532070.0